name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compilebb
      run: gcc test_iguaisaleatorios.c -0 test_iguaisaleatorios
    - name: execute
      run: ./test_iguaisaleatorios
